
CLEANFILES += docs/*.hi docs/*.o

docs/site : docs/site.hs docs/Constants.hs
	cd docs && ghc --make site.hs

.PHONY: web deploy

web : docs/site
	cd docs && ./site rebuild

deploy : web
	./docs/deploy.sh
