CLEANFILES = docs/_build docs/doxygen
SPHINXBUILD   = sphinx-build
BUILDDIR      = docs/_build
SPHINXOPTS    =

.PHONY: doc
doc :
	doxygen Doxyfile
	$(SPHINXBUILD) -b html $(SPHINXOPTS) $(top_srcdir)/docs $(BUILDDIR)/html
	@echo
	@echo "Build finished. The HTML pages are in $(BUILDDIR)/html."
